<?php
/**
 * Optional advanced configuration for Behaviour Tracker Plugin.
 *
 * Most stores can use Settings > Behaviour Tracker in WordPress admin instead.
 * Keep this file as config.php only if you need file-based overrides.
 */

return [
    // The URL where the tracking data is sent.
    // Can also be configured in Settings > Behaviour Tracker.
    'webhook_url' => 'https://tracker.yatootunisie.tn/webhook',

    // Unique identifier for this website/store (sent as site_id).
    // Can also be configured in Settings > Behaviour Tracker.
    'site_id' => 'your-store-id',

    // Public write key generated by the SaaS for this website.
    // Can also be configured in Settings > Behaviour Tracker.
    // Browser events use this key; it is validated with site_id and allowed domain.
    'write_key' => 'pk_live_your_public_write_key',

    // Server secret key generated by the SaaS for server-side events.
    // Can also be configured in Settings > Behaviour Tracker.
    // Keep this private in config.php; do not expose it in custom frontend code.
    'server_secret_key' => 'sk_live_your_server_secret_key',

    // Buffer interval in seconds (how often to send batched events)
    // Minimum: 1 second, Recommended: 5-10 seconds
    'buffer_interval' => 3,

    // ========================================
    // MASTER TRACKER SECTION CONTROLS
    // Enable/disable entire tracker sections for isolated testing
    // Set to false to completely disable a section
    // ========================================

    'enabled_sections' => [
        'session_navigation' => true,   // Session & Navigation tracking (session.js, navigation.js)
        'product' => true,              // Product Discovery tracking (product.js)
        'cart' => true,                 // Shopping Cart tracking (cart.js)
        'checkout' => true,             // Checkout & Purchase tracking (checkout.js)
        'account' => true,              // User Account tracking (account.js)
        'search' => true,               // Search & Filters tracking (search.js)
        'marketing' => true,            // Marketing & Promotions tracking (marketing.js)
    ],

    // ========================================
    // OPTIONAL SELECTOR OVERRIDES
    // Use these to support custom themes / builders.
    // Each key is an array of additional CSS selectors that will be
    // MERGED with the plugin's defaults in JS.
    // If you leave them empty, the default behaviour is unchanged.
    // ========================================

    'selectors' => [
        // Session & navigation
        'click_elements' => [
            // e.g. '.my-custom-button'
        ],

        // Product discovery
        'product_page_containers' => [
            // e.g. '.single-product-wrapper'
        ],
        'product_list_items' => [
            // e.g. '.my-product-list .product-card'
        ],

        // Cart
        'cart_rows' => [
            // e.g. '.my-cart-row'
        ],
        'cart_quantity_inputs' => [
            // e.g. 'input.my-qty'
        ],
        'coupon_forms' => [
            // e.g. 'form.my-coupon-form'
        ],

        // Checkout
        'shipping_method_inputs' => [
            // e.g. 'input[name="my_shipping_method"]'
        ],
        'payment_method_inputs' => [
            // e.g. 'input[name="my_payment_method"]'
        ],

        // Account
        'login_forms' => [
            // e.g. 'form.my-login-form'
        ],
        'register_forms' => [
            // e.g. 'form.my-register-form'
        ],
        'edit_account_forms' => [
            // e.g. 'form.my-edit-account'
        ],
        'reset_password_forms' => [
            // e.g. 'form.my-reset-password'
        ],

        // Search & filters
        'search_forms' => [
            // e.g. 'form.header-search'
        ],
        'filter_containers' => [
            // e.g. '.my-filter-widget'
        ],
        'sort_selects' => [
            // e.g. 'select.my-orderby'
        ],

        // Marketing & promotions
        'newsletter_forms' => [
            // e.g. 'form.my-newsletter'
        ],
        'banner_elements' => [
            // e.g. '.my-banner'
        ],
        'social_share_buttons' => [
            // e.g. '.my-share-button'
        ],
    ],
];
