USE tracer;

ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS metric_baseline_average_precision Nullable(Float64) AFTER metric_average_precision;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS metric_recall_top_10_pct Nullable(Float64) AFTER metric_baseline_precision_top_10_pct;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS metric_baseline_recall_top_10_pct Nullable(Float64) AFTER metric_recall_top_10_pct;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS metric_lift_top_10_pct Nullable(Float64) AFTER metric_baseline_recall_top_10_pct;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS metric_baseline_lift_top_10_pct Nullable(Float64) AFTER metric_lift_top_10_pct;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS metric_precision_top_20 Nullable(Float64) AFTER metric_baseline_lift_top_10_pct;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS metric_recall_top_20 Nullable(Float64) AFTER metric_precision_top_20;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS metric_lift_top_20 Nullable(Float64) AFTER metric_recall_top_20;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS metric_baseline_precision_top_20 Nullable(Float64) AFTER metric_lift_top_20;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS metric_baseline_recall_top_20 Nullable(Float64) AFTER metric_baseline_precision_top_20;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS metric_baseline_lift_top_20 Nullable(Float64) AFTER metric_baseline_recall_top_20;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS metric_precision_top_50 Nullable(Float64) AFTER metric_baseline_lift_top_20;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS metric_recall_top_50 Nullable(Float64) AFTER metric_precision_top_50;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS metric_lift_top_50 Nullable(Float64) AFTER metric_recall_top_50;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS metric_baseline_precision_top_50 Nullable(Float64) AFTER metric_lift_top_50;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS metric_baseline_recall_top_50 Nullable(Float64) AFTER metric_baseline_precision_top_50;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS metric_baseline_lift_top_50 Nullable(Float64) AFTER metric_baseline_recall_top_50;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS metric_precision_top_100 Nullable(Float64) AFTER metric_baseline_lift_top_50;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS metric_recall_top_100 Nullable(Float64) AFTER metric_precision_top_100;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS metric_lift_top_100 Nullable(Float64) AFTER metric_recall_top_100;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS metric_baseline_precision_top_100 Nullable(Float64) AFTER metric_lift_top_100;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS metric_baseline_recall_top_100 Nullable(Float64) AFTER metric_baseline_precision_top_100;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS metric_baseline_lift_top_100 Nullable(Float64) AFTER metric_baseline_recall_top_100;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS metric_brier Nullable(Float64) AFTER metric_baseline_lift_top_100;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS metric_threshold_precision Nullable(Float64) AFTER metric_brier;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS metric_threshold_recall Nullable(Float64) AFTER metric_threshold_precision;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS metric_threshold_f1 Nullable(Float64) AFTER metric_threshold_recall;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS decision_threshold Nullable(Float64) AFTER metric_threshold_f1;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS class_imbalance_ratio Nullable(Float64) AFTER decision_threshold;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS validation_strategy LowCardinality(String) DEFAULT '' AFTER class_imbalance_ratio;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS sampling_strategy LowCardinality(String) DEFAULT '' AFTER validation_strategy;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS train_positive_rows UInt64 DEFAULT 0 AFTER test_rows;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS test_positive_rows UInt64 DEFAULT 0 AFTER train_positive_rows;
ALTER TABLE ml_model_runs ADD COLUMN IF NOT EXISTS metrics_json String DEFAULT '' AFTER feature_count;
